### ISSUE TITLE
Graph is influenced by frame rate

### ISSUE THREAD

**Issue by retiutut** [jagracar/grafica#11]
Working on the accelerometer widget in the OpenBCI GUI to resolve this issue: https://github.com/OpenBCI/OpenBCI_GUI/issues/410

I copied the conventions already in place for data buffers, and I have a serious problem. For some reason, the new Gplot I put in place is affected by the app's framerate!!! 

For all graphs` nPoints = numSeconds*sampleRate`. This algorithm was copied to the new gPlot but it doesn't behave the same at all. The sample rate for the accelerometer data is 25Hz. Changing the framerate makes the graph update faster or slower.
![screen recording 2018-12-02 at 11 14 58 am 2018-12-02 11_16_50](https://user-images.githubusercontent.com/25914123/49342671-d0131580-f623-11e8-89fd-dbe434c7280f.gif)

![screen recording 2018-12-01 at 2 29 14 pm 2018-12-01 14_34_29](https://user-images.githubusercontent.com/25914123/49342527-24b59100-f622-11e8-8a32-14e6150d5b37.gif)

To confirm this is the problem, changing the sample rate to line up exactly with framRate makes it "look" right, but this is not good and not accurate.

I would expect a graph to run at the rate I have specified and not be affected by framerate. Any help would be appreciated.

**Comment by retiutut** [comment]
> Are you updating the frame rate of the processing sketch? That would be the first place to look at. Processing will always run at 60 fps unless you tell it to change to another value.

Yes, the user has the option to toggle 30,45, and 60fps. It defaults to 30. Running at 60 makes the Accelerometer GPlot scroll even faster, as shown in the video-gif above!

**Comment by jagracar** [comment]
Hi,

Are you using this method to set the frame rate?
https://processing.org/reference/frameRate_.html

I still think is not a problem of the grafica lib.

**Comment by retiutut** [comment]
Yes.
``` 
 if(frameRateCounter==0){
    frameRate(24); //refresh rate ... this will slow automatically, if your processor can't handle the specified rate
  }
  if(frameRateCounter==1){
    frameRate(30); //refresh rate ... this will slow automatically, if your processor can't handle the specified rate
  }
  if(frameRateCounter==2){
    frameRate(45); //refresh rate ... this will slow automatically, if your processor can't handle the specified rate
  }
  if(frameRateCounter==3){
    frameRate(60); //refresh rate ... this will slow automatically, if your processor can't handle the specified rate
  }
```

**Comment by retiutut** [comment]
```

import grafica.*;
import java.util.Random;

int padding = 25;
Random r = new Random();
boolean logScale_FFT;

int nPoints = 60;
GPlot plot, plot2;
GPointsArray points, points2;

int widthOfLastScreen;
int heightOfLastScreen;

void setup() {
  size(1024, 768);
  background(255,0,0);
  
  frameRate(30);
  
  surface.setResizable(true);
  widthOfLastScreen = width; //for screen resizing (Thank's Tao)
  heightOfLastScreen = height;

  // Prepare the points for the plot
  points = new GPointsArray(nPoints);
  points2 = new GPointsArray(nPoints);
  
  for (int i = 0; i < nPoints; i++) {
    points.add(i, 15*noise(0.1*i));
  }
  
  for (int i = 0; i < nPoints; i++) {
    float x = 10 + random(200);
    float y = 10*exp(0.015*x);
    float xErr = 2*((float) r.nextGaussian());
    float yErr = 2*((float) r.nextGaussian());
    points2.add(x + xErr, y + yErr);
  }

  // Create a new plot and set its position on the screen
  plot = new GPlot(this, padding, padding, (width-(4*padding))/2, 300);
  plot2 = new GPlot(this, width/2 + padding, padding, (width-(4*padding))/2, 300);
  plot.setPos(padding, padding);
  //plot2.setPos(padding, padding);
  // or all in one go
  // GPlot plot = new GPlot(this, 25, 25);
  
  logScale_FFT = true;

  // Set the plot title and the axis labels
  plot.setTitleText("EEG Montage");
  plot.getXAxis().setAxisLabelText("x axis");
  plot.getYAxis().setAxisLabelText("y axis");
  
  //plot 2
  plot2.setTitleText("FFT Plot");
  plot2.getXAxis().setAxisLabelText("x axis");
  plot2.getYAxis().setAxisLabelText("y axis");
  //plot2.setMar(50,50,50,50); //{ bot=60, left=70, top=40, right=30 } by default
  plot2.setMar(60,70,40,30); //{ bot=60, left=70, top=40, right=30 } by default
  plot2.setLogScale("y");
  
  int upperY = 100;
  plot2.setYLim(0.1,100);
  int _nTicks = int(upperY/10 - 1);
  plot2.getYAxis().setNTicks(_nTicks);  //sets the number of axis divisions...
  plot2.setXLim(0.1,60);
  plot2.getYAxis().setDrawTickLabels(true);
  plot2.setPointSize(2);
  plot2.setPointColor(0);
  
  //plot2.setLogScale(""); //sets it back to non-logarithmic

  // Add the points
  plot.setPoints(points);
  plot2.setPoints(points);
}

void draw(){
  
  if (widthOfLastScreen != width || heightOfLastScreen != height) {
    println("OpenBCI_GUI: setup: RESIZED");
    //screenHasBeenResized = true;
    //timeOfLastScreenResize = millis();
    updateGraphs();
    widthOfLastScreen = width;
    heightOfLastScreen = height;
  }
  
  //updatePoints
  for (int i = 0; i < nPoints; i++) {
    //GPoint temp = new GPoint(i, 15*noise(0.1*i));
    GPoint temp = new GPoint(i, 15*random(0.1*i));
    points.set(i, temp);
  }
  
  plot.setPoints(points);
  plot2.setPoints(points);
  
  
  // Draw it!
  plot.defaultDraw();
  
  plot2.beginDraw();
  plot2.drawBackground();
  plot2.drawBox();
  plot2.drawXAxis();
  plot2.drawYAxis();
  plot2.drawTopAxis();
  plot2.drawRightAxis();
  plot2.drawTitle();
  plot2.drawGridLines(2);
  plot2.drawLines();
  plot2.drawPoints(); //draw points
  plot2.endDraw();
  
}

void updateGraphs(){
  //plot1
  plot.setPos(padding, padding);//update position
  plot.setOuterDim((width-(4*padding))/2, 300);//update dim
  
  //plot2
  plot2.setPos(width/2 + padding, padding);//update position
  plot2.setOuterDim((width-(4*padding))/2, 300);//update dim
}

void mouseClicked() {
  // Change the log scale
  logScale_FFT = !logScale_FFT;
  
  if (logScale_FFT) {
    plot2.setLogScale("y");
    plot2.getYAxis().setAxisLabelText("log y");
  }
  else {
    plot2.setLogScale("");
    plot2.getYAxis().setAxisLabelText("y");
  }
}
```

**Comment by jagracar** [comment]
Ok, thanks,

I think I understand now the problem. How is the scrolling implemented? You are subtracting a delta time to each x (time) value each frame? Is each plot draw in a different thread or they are plotted in inside the same draw() method? My guess is that it has something to do with the frame rate implemented in processing. It doesn't grant that it's constant. 

For example if you add this line at the beginning of the draw method:

`  println(frameRate);
`
and set the frame rate to 3, you will see that it starts printing values of 9 and slowly approaches 3.

In addition to that, if you calculate too many things per frame, it could be that you cannot read very high frame rates. Your top panel seems to have many more points than the bottom panel. Maybe the top panel cannot run at the specified frame rate and that's why is seems to move slower?

What do you get if you print the frame rate just before each plot is draw? My guess is that each plot is seeing a different frame rate.

**Comment by retiutut** [comment]
https://github.com/retiutut/OpenBCI_GUI/blob/development/OpenBCI_GUI/W_accelerometer.pde

**Comment by retiutut** [comment]
> What do you get if you print the frame rate just before each plot is draw? My guess is that each plot is seeing a different frame rate.
```
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS TS: 29.432238
FPS accel: 29.432238
```
Placed before drawing the plot in both Widgets. Somehow, the Time Series prints 8 times for every 1 of Accelerometer widget

**Comment by jagracar** [comment]
Yes, I was going to write that :) 8 time series vs one acc.

I will have a look at the code.

**Comment by retiutut** [comment]
> Yes, I was going to write that :) 8 time series vs one acc.
> 
> I will have a look at the code.

Yes, it depends on the number of channels being used (4,8, or 16). At least the Time Series works correctly, aka 8 graphs work properly and not influenced by framerate with 1 bad apple.

**Comment by jagracar** [comment]
Well, they are called inside the same class, that's why the do the same.

I think the problem must be in these two methods:

Can you

**Comment by jagracar** [comment]
And also the value of  the timeBetweenPoints variable. It should be the same in both panels, right?

**Comment by retiutut** [comment]
> I think the problem must be in these two methods:
> https://github.com/retiutut/OpenBCI_GUI/blob/development/OpenBCI_GUI/W_accelerometer.pde#L569
> https://github.com/retiutut/OpenBCI_GUI/blob/development/OpenBCI_GUI/W_TimeSeries.pde#L527

There is nothing wrong with the method in Time Series.

The problem is with Accelerometer. I did my best to copy the structure.

**Comment by retiutut** [comment]
> And also the value of the timeBetweenPoints variable. It should be the same in both panels, right?
```
TIME BETWEEN POINTS = 0.004
NUMBER OF POINTS = 1250
ChannelController: createChannelSettingButtons: creating channel setting buttons...
init accelerometer bar
TIME BETWEEN POINTS = 0.04
NUMBER OF POINTS = 500
```

**Comment by jagracar** [comment]
I see that you initialize the array accelTimeArray in the AccelerometerBar constructor and you never update it later:

```
accelTimeArray = new float[nPoints];
    for (int i = 0; i < accelTimeArray.length; i++) {
      accelTimeArray[i] = -(float)numSeconds + (float)i * timeBetweenPoints;
    }

```

If timeBetweenPoints changes, because accelHz changes, the array values will be  wrong. And you are using the array to set the points x (time) values.

On the other side, the time series class is calculating the time each frame, so if numSeconds is updated by  the adjustTimeAxis method  the time will be updated, but your accelTimeArray array won't.

Could that be?

**Comment by jagracar** [comment]
even if adjustTimeAxis(int _newTimeSize) is run during execution?

In that case numSeconds will change and timeBetweenPoints = numSeconds / nPoints

**Comment by retiutut** [comment]
Yes, it updates properly.

**Comment by retiutut** [comment]
What I've noticed is that the Points in the array are updating faster/slower based on framerate, and then fed to Gplot. So the Gplot is updated with new Gpoints after an append and shift in the buffer. This happens here:

https://github.com/retiutut/OpenBCI_GUI/blob/1d97d4b1ad3ea531b3d425a07220c65ee4529225/OpenBCI_GUI/W_accelerometer.pde#L179

**Comment by retiutut** [comment]
Fixed 🔥
Closing this issue ✅

Updating points for a Gplot during draw() or update() causes data to generate incorrectly. The following code is quite successful. Tested first with just the X axis.

```
  //Used to update the Points within the graph
  void updateGPlotPoints(){
    int accelBuffSize = w_accelerometer.accelBuffSize;

    // update data in plot
    int numSamplesToProcess = curDataPacketInd - lastProcessedDataPacketInd;
    if (numSamplesToProcess < 0) {
      numSamplesToProcess += dataPacketBuff.length;
    }

    // Shift internal ring buffer numSamplesToProcess
    if (numSamplesToProcess > 0) {
      for(int i = 0; i < accelArrayX.length - numSamplesToProcess; i++){
        accelArrayX[i] = accelArrayX[i + numSamplesToProcess];
      }
    }

    // for each new sample
    int samplesProcessed = 0;
    while (samplesProcessed < numSamplesToProcess) {
      lastProcessedDataPacketInd++;

      // Watch for wrap around
      if (lastProcessedDataPacketInd > dataPacketBuff.length - 1) {
        lastProcessedDataPacketInd = 0;
      }
      //println(numSamplesToProcess + samplesProcessed);
      accelArrayX[accelBuffSize - numSamplesToProcess + samplesProcessed] = w_accelerometer.currentXvalue;

      samplesProcessed++;
    }

    //println("UPDATING ACCEL GRAPH");
    int accelBuffDiff = accelBuffSize - nPoints;
    if (numSamplesToProcess > 0) {
      for (int i = accelBuffDiff; i < accelBuffSize; i++) { //same method used in W_TimeSeries
        //float time = -(float)numSeconds + (float)(i-(accelBuffDiff))*timeBetweenPoints;
        //println(time);
        GPoint tempPointX = new GPoint(accelTimeArray[i-accelBuffDiff], accelArrayX[i]);
        GPoint tempPointY = new GPoint(accelTimeArray[i-accelBuffDiff], accelArrayY[i]);
        GPoint tempPointZ = new GPoint(accelTimeArray[i-accelBuffDiff], accelArrayZ[i]);
        accelPointsX.set(i-accelBuffDiff, tempPointX);
        accelPointsY.set(i-accelBuffDiff, tempPointY);
        accelPointsZ.set(i-accelBuffDiff, tempPointZ);
      }
      plot.setPoints(accelPointsX, "layer 1");
      plot.setPoints(accelPointsY, "layer 2");
      plot.setPoints(accelPointsZ, "layer 3");
    }
  }
```
